apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: init-venv
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  desciption: >-
    This task will create a Python virtual env using a requirements.txt file
  
  workspaces:
    - name: source
  params:
    - name: requirements_file
      description: Name of the requirements file
      default: "requirements.txt"
    - name: venv_dir
      description: Dir used for creating the Virtual environment
      default: ".venv"
    - name: image
      default: "python:alpine"
  steps:
    - name: venv
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      script: |
        python3 -m venv $(workspaces.source.path)/$(params.venv_dir)
        source $(workspaces.source.path)/$(params.venv_dir)/bin/activate
        pip install -f $(workspaces.source.path)/$(params.requirements_file)
