---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pylint
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Code Quality
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: python, pylint
    tekton.dev/displayName: pylint
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task will run pylint on the provided input.

  workspaces:
    - name: source
  params:
    - name: image
      description: The container image with pylint
      default: python:alpine
    - name: venv_dir
      description: Dir used for creating the Virtual environment
      default: ".venv"
    - name: path
      description: The path to the module which should be analysed by pylint
      default: "."
      type: string
    - name: args
      description: The arguments to pass to the pylint CLI.
      type: array
      default: []
  steps:
    - name: pylint
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      script: |
        export PATH=$PATH:$HOME/.local/bin
        source $(workspaces.source.path)/$(params.venv_dir)/bin/activate
        pip install pylint
        pylint $@ "$(params.path)"
      args:
        - "$(params.args)"
