---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pytest
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/categories: Testing
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: python, pytest
    tekton.dev/displayName: pytest
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This task will run pytest on the provided input.

  workspaces:
    - name: source
    - description: The workspace consisting of the custom pip settings.
      name: pip-conf
      optional: true
  params:
    - name: PYTHON_IMAGE
      description: The used Python image
      type: string
      default: "python:alpine"
    - name: ARGS
      description: The additional arguments to be used with pytest
      type: string
      default: ""
    - name: SOURCE_PATH
      description: The path to the source code
      default: "."
    - name: VENV_PATH
      desciption: Path to virtual env
      default: ".venv"
  steps:
    - name: unit-test
      image: $(params.PYTHON_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        export PATH=$PATH:$HOME/.local/bin
        source $(params.VENV_PATH)/.venv/bin/activate

        if [ -z "$(params.ARGS)" ]; then
          python3 -m pytest "$(params.SOURCE_PATH)"
        else
          python3 -m pytest "$(params.ARGS)" "$(params.SOURCE_PATH)"
        fi
