apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: flask-ci-pipeline
spec:
  params:
    - name: repo_url
      type: string
    - name: revision
      type: string
    - name: image
      type: string
  workspaces:
    - name: source
    - name: basic-auth
    - name: dockerconfig
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    - name: linting
      taskRef: 
        name: pylint
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
    - name: unit-testing
      taskRef: 
        name: pytest
      runAfter:
        - linting
      workspaces:
        - name: source
          workspace: source
    - name: build-image
      taskRef:
        name: kaniko
      runAfter:
        - unit-testing
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: IMAGE
          value: $(params.image)
